version: '3'
services:
  ubuntu:
    build:
      context: .
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
    image: palworld:latest
    environment:
        EULA: "TRUE"
    tty: true
    stdin_open: true
    volumes:
      - ./server:/home/gameadmin/server/:rw
    ports:
      - 25565:25565/udp
      - 25575:25575/tcp
    command: ["sleep","infinity"]